language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bugrauluyurt/react-test -f./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bugrauluyurt/react-test npm test

after_success:
  - docker build -t bugrauluyurt/docker-multi-client ./client
  - docker build -t bugrauluyurt/docker-multi-server ./server
  - docker build -t bugrauluyurt/docker-multi-worker ./worker
  - docker build -t bugrauluyurt/docker-multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to dockerhub
  - docker push bugrauluyurt/docker-multi-client
  - docker push bugrauluyurt/docker-multi-server
  - docker push bugrauluyurt/docker-multi-worker
  - docker push bugrauluyurt/docker-multi-nginx